var DEBUG_MODE = false;
var DEV_MODE = false;

enum StorageKeys {
    STORAGE_LOCATION,
    STORAGE_UV_DATA
}

enum UVIndex {
    UV_INDEX_NONE,
    UV_INDEX_LOW,
    UV_INDEX_MEDIUM,
    UV_INDEX_HIGH,
    UV_INDEX_VERY_HIGH,
    UV_INDEX_EXTREME,
    UV_INDEX_UNKNOWN
}